on:
  pull_request:
  merge_group:

name: probe-plotter-tools

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Install libudev (linux)
        run: |
          sudo apt update
          sudo apt install -y libudev-dev

      - name: Format
        working-directory: ./probe-plotter-tools
        run: cargo fmt
      - name: Regular build
        working-directory: ./probe-plotter-tools
        run: cargo check
      - name: Clippy
        working-directory: ./probe-plotter-tools
        run: cargo clippy
